status command error is captured and counted 	modified:   .github/workflows/gridai_run.yml

diff --git a/.github/workflows/gridai_run.yml b/.github/workflows/gridai_run.yml
--- a/.github/workflows/gridai_run.yml
+++ b/.github/workflows/gridai_run.yml
@@ -29,7 +29,11 @@ on:
       max_sec_run:
         required: false
         default: 120
-        type: string       
+        type: string      
+      max_cmd_err_cnt: 
+        required: false
+        default: 10
+        type: string      
     secrets:
       username:
         required: true
@@ -60,16 +64,28 @@ jobs:
           if [[ -z "${RUN_NAME}" ]]; then
             echo "Error: grid_name not found in output"
             exit 1
-          fi
+          fi 
       - run: |
+          cmd_err_cnt=0
           JSON_FILE=$(grid status --export json ${RUN_NAME} | grep Exported | awk '{print $5}')
           RUN_STATUS=$(cat ${JSON_FILE} | jq -r -c '.[] | .status')
           # pool at 1 min interval
-          while [ "${RUN_STATUS}" = 'queued' -o "${RUN_STATUS}" = 'running' -o "${RUN_STATUS}" = 'pending' ]; do 
+          while [ "${RUN_STATUS}" = 'queued' -o "${RUN_STATUS}" = 'running' -o "${RUN_STATUS}" = 'pending' -o "${RUN_STATUS}" = 'unknown' ]; do 
             echo "${RUN_NAME}:${RUN_STATUS} waiting ${{ inputs.poll_sec_interval }} sec for the next status"
             sleep ${{ inputs.poll_sec_interval }}
-            JSON_FILE=$(grid status --export json ${RUN_NAME} | grep Exported | awk '{print $5}')
-            RUN_STATUS=$(cat ${JSON_FILE} | jq -r -c '.[] | .status')
+            grid status --export json ${RUN_NAME} > grid.status.log 2>&1
+            if [[ "$?" != 0 ]]; then
+              (( cmd_err_cnt = cmd_err_cnt + 1 ))
+              echo "Error from grid status command: # ${cmd_err_cnt}"
+              cat grid.status.log
+              RUN_STATUS="unknown"
+              if [[ ( ${cmd_err_cnt} ) > ${{ inputs.max_cmd_err_cnt}} ]]; then
+                break
+              fi
+            else  
+              JSON_FILE=$( | grep Exported | awk '{print $5}')
+              RUN_STATUS=$(cat ${JSON_FILE} | jq -r -c '.[] | .status')
+            fi
           done
           echo "${RUN_NAME}:${RUN_STATUS}"
           # only continue on successful completion
